# Generated by Django 4.0.5 on 2022-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('num_venda', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('cpf_vendedor', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nome_vendedor', models.CharField(max_length=30)),
                ('data_admissao', models.DateField(auto_now=True)),
                ('salario_bruto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('salario_liquido', models.DecimalField(decimal_places=2, max_digits=9)),
                ('percentual_comissao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('quantidade_vendas', models.IntegerField(max_length=5)),
            ],
        ),
    ]
