# Generated by Django 4.0.5 on 2022-07-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='cpf_vendedor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='quantidade_vendas',
            field=models.IntegerField(),
        ),
    ]
