# Generated by Django 4.0.4 on 2022-07-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vendedor_cpf_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=30)),
                ('nivel', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('num_produto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=30)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantidade_produto', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='cpf_vendedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.vendedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='percentual_desc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Venda_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('cod_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('num_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='cpf_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
            preserve_default=False,
        ),
    ]
