# Generated by Django 4.0.4 on 2022-07-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_produto_venda_cpf_vendedor_venda_data_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cliente',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='num_produto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venda',
            name='num_venda',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cpf_vendedor',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
