# Generated by Django 4.0.4 on 2022-07-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_cpf_cliente_alter_produto_num_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cod_produto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cpf_cliente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cpf_vendedor',
            field=models.IntegerField(default=0),
        ),
    ]
